HW Questions (Numpy):
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [12]:
import numpy as np

A = np.array([1, 2, 3])
print(A)

B = np.array([7, 8, 9])
print(B)

vertical_stack = np.vstack((A, B))
print("stacking A and B vertically:")
print(vertical_stack)

horizontally_stack = np.hstack((A, B))
print("stacking A and B horizontally:")
print(horizontally_stack)


[1 2 3]
[7 8 9]
stacking A and B vertically:
[[1 2 3]
 [7 8 9]]
stacking A and B horizontally:
[1 2 3 7 8 9]


2. Find common elements between A and B. [Hint: Intersection of two sets]

In [13]:
import numpy as np

A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([4, 5, 6, 7, 8])

common_elements = np.intersect1d(A, B)

print("common elements between A and B ")
print(common_elements)

common elements between A and B 
[4 5 6]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [16]:
import numpy as np

A = np.arange(21)

print(A)

mask = (A > 5) & (A < 10)

#print("(A > 5) & (A < 10):")
#print(mask)

extracted_numbers = A[mask]

print("The result of the extracted number :")
print(extracted_numbers)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
The result of the extracted number :
[6 7 8 9]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [19]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#print(" Original Iris Data ")
#print(iris_2d)

# Condition for petallength (3rd column) > 1.5
condition_1 = iris_2d[:, 2] > 1.5

# Condition for sepallength (1st column) < 5.0
condition_2 = iris_2d[:, 0] < 5.0

combined_mask = (condition_1) & (condition_2)

filtered_rows = iris_2d[combined_mask]

print("After filter")
print(filtered_rows)


After filter
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


HW Questions (Pandas):
1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [23]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [33]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

mean_min_price = df['Min.Price'].mean()
mean_max_price = df['Max.Price'].mean()

df['Min.Price'].fillna(mean_min_price, inplace=True)
df['Max.Price'].fillna(mean_max_price, inplace=True)

# verify
print("After Replace Missing Values")
print(df[['Min.Price', 'Max.Price']].isnull().sum())

After Replace Missing Values
Min.Price    0
Max.Price    0
dtype: int64


/var/folders/s5/1lmxvww93pbfs820tmmc_8mm0000gn/T/ipykernel_96353/3051132061.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(mean_min_price, inplace=True)
/var/folders/s5/1lmxvww93pbfs820tmmc_8mm0000gn/T/ipykernel_96353/3051132061.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values 

3. How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [36]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

row_sums = df.sum(axis=1)

mask = row_sums > 100

filtered_df = df[mask]

print("Rows sum > 100")
print(filtered_df)

Rows sum > 100
     0   1   2   3
1   33  19  36  31
2   30  26  23  22
3   38  37  35  13
6   38  14  34  31
7   33  16  25  38
12  30  16  29  32
13  25  27  31  33
